export async function seedNetworkLinks({
  db,
  networkLinksTable,
  managedDevices,
  customers,
  sites,
  ctrlNow,
}: any) {
  const [
    mxHQActive,
    mxHQSpare,
    mxDenver,
    mxAustin,
    mxPhoenix,
    mxDallasDC,
    fgtHQPrimary,
    fgtHQStandby,
    fgtChicago,
  ] = managedDevices;

  const { nexatek, convergex, pinnacle } = customers;
  const { nxtHQ, nxtDenver, nxtAustin, nxtPhoenix, nxtDC, cvxHQ, pnlMemphis } = sites;

  const inserted = await db
    .insert(networkLinksTable)
    .values([
      {
        managedDeviceId: mxHQActive.id,
        customerId: nexatek.id,
        siteId: nxtHQ.id,
        linkName: 'WAN1 — Zayo',
        linkType: 'internet',
        providerName: 'Zayo',
        circuitId: 'ZYO-DIA-HQ-001',
        role: 'primary',
        status: 'up',
        networkName: 'Nexatek — HQ Chicago',
        latencyMs: 7.4,
        jitterMs: 0.3,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 90 * 1000),
        metadataJson: {
          interface: 'WAN1',
          ip: '203.0.113.5',
          publicIp: '203.0.113.5',
          merakiStatus: 'active',
        },
      },
      {
        managedDeviceId: mxHQActive.id,
        customerId: nexatek.id,
        siteId: nxtHQ.id,
        linkName: 'WAN2 — Comcast Business',
        linkType: 'internet',
        providerName: 'Comcast Business',
        circuitId: 'CMC-BIZ-HQ-002',
        role: 'backup',
        status: 'up',
        networkName: 'Nexatek — HQ Chicago',
        latencyMs: 12.1,
        jitterMs: 1.0,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 90 * 1000),
        metadataJson: {
          interface: 'WAN2',
          ip: '98.27.44.190',
          publicIp: '98.27.44.190',
          merakiStatus: 'ready',
        },
      },
      {
        managedDeviceId: mxDenver.id,
        customerId: nexatek.id,
        siteId: nxtDenver.id,
        linkName: 'WAN1 — Comcast Business',
        linkType: 'broadband',
        providerName: 'Comcast Business',
        circuitId: 'CMC-BIZ-190224-B',
        role: 'primary',
        status: 'down',
        networkName: 'Nexatek — Denver Warehouse',
        packetLossPct: 100,
        failoverActive: false,
        lastPolledAt: new Date(ctrlNow.getTime() - 2.5 * 3600 * 1000),
        metadataJson: {
          interface: 'WAN1',
          merakiStatus: 'failed',
          lastStatusChange: new Date(ctrlNow.getTime() - 2.5 * 3600 * 1000).toISOString(),
        },
      },
      {
        managedDeviceId: mxDenver.id,
        customerId: nexatek.id,
        siteId: nxtDenver.id,
        linkName: 'Cellular — AT&T [Failover Active]',
        linkType: 'lte',
        providerName: 'AT&T',
        role: 'backup',
        status: 'up',
        networkName: 'Nexatek — Denver Warehouse',
        failoverActive: true,
        latencyMs: 55.3,
        jitterMs: 6.1,
        packetLossPct: 0.8,
        lastPolledAt: new Date(ctrlNow.getTime() - 2.5 * 3600 * 1000),
        metadataJson: {
          interface: 'Cellular',
          ip: '10.128.0.5',
          publicIp: '72.14.195.201',
          merakiStatus: 'active',
          failoverActive: true,
        },
      },
      {
        managedDeviceId: mxAustin.id,
        customerId: nexatek.id,
        siteId: nxtAustin.id,
        linkName: 'WAN1 — AT&T Business Fiber',
        linkType: 'internet',
        providerName: 'AT&T Business Fiber',
        circuitId: 'ATT-BIZ-AUS-101',
        role: 'primary',
        status: 'up',
        networkName: 'Nexatek — Austin Office',
        latencyMs: 11.2,
        jitterMs: 0.9,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 60 * 1000),
        metadataJson: { interface: 'WAN1', ip: '12.141.99.44', merakiStatus: 'active' },
      },
      {
        managedDeviceId: mxAustin.id,
        customerId: nexatek.id,
        siteId: nxtAustin.id,
        linkName: 'WAN2 — Spectrum Business',
        linkType: 'internet',
        providerName: 'Spectrum Business',
        role: 'backup',
        status: 'up',
        networkName: 'Nexatek — Austin Office',
        latencyMs: 18.4,
        jitterMs: 2.1,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 60 * 1000),
        metadataJson: { interface: 'WAN2', ip: '76.220.14.88', merakiStatus: 'ready' },
      },
      {
        managedDeviceId: mxPhoenix.id,
        customerId: nexatek.id,
        siteId: nxtPhoenix.id,
        linkName: 'WAN1 — Cox Business',
        linkType: 'internet',
        providerName: 'Cox Business',
        circuitId: 'COX-BIZ-PHX-044',
        role: 'primary',
        status: 'up',
        networkName: 'Nexatek — Phoenix Retail',
        latencyMs: 9.8,
        jitterMs: 0.7,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 45 * 1000),
        metadataJson: { interface: 'WAN1', ip: '67.199.143.88', merakiStatus: 'active' },
      },
      {
        managedDeviceId: mxPhoenix.id,
        customerId: nexatek.id,
        siteId: nxtPhoenix.id,
        linkName: 'WAN2 — Verizon LTE',
        linkType: 'lte',
        providerName: 'Verizon LTE',
        role: 'backup',
        status: 'up',
        networkName: 'Nexatek — Phoenix Retail',
        latencyMs: 38.2,
        jitterMs: 4.5,
        packetLossPct: 0.1,
        lastPolledAt: new Date(ctrlNow.getTime() - 45 * 1000),
        metadataJson: { interface: 'WAN2', ip: '172.58.99.4', merakiStatus: 'ready' },
      },
      {
        managedDeviceId: mxDallasDC.id,
        customerId: nexatek.id,
        siteId: nxtDC.id,
        linkName: 'WAN1 — Zayo 10G',
        linkType: 'internet',
        providerName: 'Zayo 10G',
        circuitId: 'ZYO-DIA-DAL-10G-005',
        role: 'primary',
        status: 'up',
        networkName: 'Nexatek — Dallas DC',
        latencyMs: 5.1,
        jitterMs: 0.2,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 30 * 1000),
        metadataJson: {
          interface: 'WAN1',
          ip: '208.55.248.12',
          publicIp: '208.55.248.12',
          merakiStatus: 'active',
        },
      },
      {
        managedDeviceId: mxDallasDC.id,
        customerId: nexatek.id,
        siteId: nxtDC.id,
        linkName: 'WAN2 — Lumen MPLS',
        linkType: 'mpls',
        providerName: 'Lumen MPLS',
        circuitId: 'LMN-MPLS-DAL-006',
        role: 'backup',
        status: 'up',
        networkName: 'Nexatek — Dallas DC',
        latencyMs: 8.3,
        jitterMs: 0.5,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 30 * 1000),
        metadataJson: {
          interface: 'WAN2',
          ip: '66.28.112.44',
          publicIp: '66.28.112.44',
          merakiStatus: 'active',
          dualHomed: true,
        },
      },
      {
        managedDeviceId: fgtHQPrimary.id,
        customerId: convergex.id,
        siteId: cvxHQ.id,
        linkName: 'WAN1 - Zayo Fiber',
        linkType: 'internet',
        providerName: 'Zayo',
        circuitId: 'ZYO-DIA-882901-Z',
        role: 'primary',
        status: 'up',
        latencyMs: 6.1,
        jitterMs: 0.3,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 5 * 60 * 1000),
        metadataJson: { interface: 'wan1', sdwanMember: 1 },
      },
      {
        managedDeviceId: fgtHQPrimary.id,
        customerId: convergex.id,
        siteId: cvxHQ.id,
        linkName: 'WAN2 - Lumen MPLS',
        linkType: 'mpls',
        providerName: 'Lumen',
        circuitId: 'LMN-MPLS-449102-M',
        role: 'backup',
        status: 'up',
        latencyMs: 15.4,
        jitterMs: 1.2,
        packetLossPct: 0.0,
        lastPolledAt: new Date(ctrlNow.getTime() - 5 * 60 * 1000),
        metadataJson: { interface: 'wan2', sdwanMember: 2 },
      },
      {
        managedDeviceId: fgtChicago.id,
        customerId: pinnacle.id,
        siteId: pnlMemphis.id,
        linkName: 'WAN1 - Comcast Fiber',
        linkType: 'internet',
        providerName: 'Comcast Business',
        circuitId: 'CMC-BIZ-551033-D',
        role: 'primary',
        status: 'degraded',
        latencyMs: 142.8,
        jitterMs: 38.5,
        packetLossPct: 12.3,
        lastPolledAt: new Date(ctrlNow.getTime() - 12 * 60 * 1000),
        metadataJson: { interface: 'wan1', sdwanHealthCheck: 'failing' },
      },
    ])
    .returning();

  return inserted;
}
