export async function seedServices(db: any, servicesTable: any, nexatek: any, ridgeline: any, broadfields: any, convergex: any, pinnacle: any, nxtDC: any, nxtHQ: any, nxtWarehouse: any, rdgNashville: any, rdgKnoxville: any, brfChicago: any, brfRockford: any, cvxAustinDC: any, pnlMemphis: any) {
  console.log('Creating services...');
  const [
    svcNxtZayo,
    svcNxtLumen,
    svcNxtCradlepoint,
    svcRdgATT1,
    svcRdgATT2,
    svcBrfComcast,
    svcBrfSpectrum,
    svcCvxZayo,
    svcCvxCogent,
    svcPnlWindstream,
    svcPnlVerizonWireless,
    svcRdgCenturyLink,
  ] = await db
    .insert(servicesTable)
    .values([
      // Nexatek DFW DC — Zayo 10G
      {
        customerId: nexatek.id,
        siteId: nxtDC.id,
        vendorName: 'Zayo',
        serviceType: 'DIA',
        circuitId: 'ZAYO/GNRN/334821/NTXK',
        bandwidth: '10Gbps',
        status: 'active',
        installDate: '2022-03-15',
        monthlyRecurringCharge: '9800.00',
        supportReference: 'ZYO-DC-00441',
        notes: 'Primary circuit. Cross-connect to Equinix DA1 meet-me room.',
      },
      // Nexatek DFW DC — Lumen 10G backup
      {
        customerId: nexatek.id,
        siteId: nxtDC.id,
        vendorName: 'Lumen',
        serviceType: 'DIA',
        circuitId: 'CLEC/LUMN/TX.DAL.29871.NTXK',
        bandwidth: '10Gbps',
        status: 'active',
        installDate: '2022-03-15',
        monthlyRecurringCharge: '8500.00',
        supportReference: 'LMN-TX-00872',
        notes: 'Secondary/failover circuit. Auto-fail controlled via BGP.',
      },
      // Nexatek HQ — Cradlepoint 4G/5G failover
      {
        customerId: nexatek.id,
        siteId: nxtHQ.id,
        vendorName: 'Cradlepoint',
        serviceType: 'Wireless',
        circuitId: 'CRPT-TX-HQ-5G-0021',
        bandwidth: '150Mbps',
        status: 'active',
        installDate: '2023-01-10',
        monthlyRecurringCharge: '420.00',
        notes: 'LTE/5G wireless failover. Active only when primary DIA fails.',
      },
      // Ridgeline Nashville — AT&T Fiber DIA
      {
        customerId: ridgeline.id,
        siteId: rdgNashville.id,
        vendorName: 'AT&T',
        serviceType: 'DIA',
        circuitId: 'ATT/TN.NSH.88172/RDGH',
        bandwidth: '1Gbps',
        status: 'active',
        installDate: '2021-06-01',
        monthlyRecurringCharge: '3200.00',
        supportReference: 'ATT-TN-54821',
        notes: 'Primary EHR and VoIP circuit. Redundancy required at all times.',
      },
      // Ridgeline Nashville — AT&T backup DIA
      {
        customerId: ridgeline.id,
        siteId: rdgNashville.id,
        vendorName: 'AT&T',
        serviceType: 'DIA',
        circuitId: 'ATT/TN.NSH.88173/RDGH',
        bandwidth: '500Mbps',
        status: 'down',
        installDate: '2021-06-01',
        monthlyRecurringCharge: '2100.00',
        supportReference: 'ATT-TN-54822',
        notes: 'CURRENTLY DOWN — backup DIA. Failover to primary activated.',
      },
      // Broadfields Chicago — Comcast Business
      {
        customerId: broadfields.id,
        siteId: brfChicago.id,
        vendorName: 'Comcast Business',
        serviceType: 'Broadband',
        circuitId: 'CMC/IL.CHI.E209-4417/BRF',
        bandwidth: '500Mbps',
        status: 'active',
        installDate: '2020-09-20',
        monthlyRecurringCharge: '720.00',
        supportReference: 'CMCB-CHI-00129',
      },
      // Broadfields Rockford — Spectrum
      {
        customerId: broadfields.id,
        siteId: brfRockford.id,
        vendorName: 'Spectrum Business',
        serviceType: 'Broadband',
        circuitId: 'SPT/IL.RFD.338821/BRF',
        bandwidth: '200Mbps',
        status: 'impaired',
        installDate: '2021-03-05',
        monthlyRecurringCharge: '380.00',
        notes: 'Currently showing intermittent speed drops. Ticket open.',
      },
      // ConvergeX Austin DC — Zayo 10G
      {
        customerId: convergex.id,
        siteId: cvxAustinDC.id,
        vendorName: 'Zayo',
        serviceType: 'DIA',
        circuitId: 'ZAYO/GNRN/441023/CVGX',
        bandwidth: '10Gbps',
        status: 'active',
        installDate: '2023-05-12',
        monthlyRecurringCharge: '10400.00',
        supportReference: 'ZYO-AUS-00882',
        notes: 'Carrier Ethernet to QTS Austin DC. BGP dual-stack.',
      },
      // ConvergeX Austin DC — Cogent backup
      {
        customerId: convergex.id,
        siteId: cvxAustinDC.id,
        vendorName: 'Cogent',
        serviceType: 'DIA',
        circuitId: 'CGNT/TX.AUS.82991/CVGX',
        bandwidth: '1Gbps',
        status: 'active',
        installDate: '2023-05-12',
        monthlyRecurringCharge: '1800.00',
        notes: 'Secondary transit. AS174 peering. BGP failover.',
      },
      // Pinnacle Memphis — Windstream
      {
        customerId: pinnacle.id,
        siteId: pnlMemphis.id,
        vendorName: 'Windstream',
        serviceType: 'Broadband',
        circuitId: 'WDST/TN.MEM.119041/PNL',
        bandwidth: '200Mbps',
        status: 'active',
        installDate: '2022-11-01',
        monthlyRecurringCharge: '340.00',
        supportReference: 'WIN-MEM-00394',
      },
      // Pinnacle Memphis — Verizon 5G wireless backup
      {
        customerId: pinnacle.id,
        siteId: pnlMemphis.id,
        vendorName: 'Verizon Business',
        serviceType: 'Wireless',
        circuitId: 'VZB/5G-FRXD-TN.MEM.2240',
        bandwidth: '100Mbps',
        status: 'active',
        installDate: '2023-07-15',
        monthlyRecurringCharge: '290.00',
        notes: '5G fixed wireless backup on Cradlepoint E3000.',
      },
      // Ridgeline Knoxville — Lumen/CenturyLink
      {
        customerId: ridgeline.id,
        siteId: rdgKnoxville.id,
        vendorName: 'Lumen',
        serviceType: 'DIA',
        circuitId: 'CLEC/LUMN/TN.KNX.40021/RDGH',
        bandwidth: '500Mbps',
        status: 'active',
        installDate: '2022-02-14',
        monthlyRecurringCharge: '2200.00',
        supportReference: 'LMN-TN-01182',
      },
    ])
    .returning();

  return {
    svcNxtZayo,
    svcNxtLumen,
    svcNxtCradlepoint,
    svcRdgATT1,
    svcRdgATT2,
    svcBrfComcast,
    svcBrfSpectrum,
    svcCvxZayo,
    svcCvxCogent,
    svcPnlWindstream,
    svcPnlVerizonWireless,
    svcRdgCenturyLink,
  };
}
