export async function seedSites(db: any, sitesTable: any, nexatek: any, ridgeline: any, broadfields: any, convergex: any, pinnacle: any) {
  console.log('Creating sites...');
  const [
    nxtHQ,
    nxtDC,
    nxtWarehouse,
    nxtDenver,
    nxtAustin,
    nxtPhoenix,
    rdgNashville,
    rdgKnoxville,
    brfChicago,
    brfRockford,
    cvxAustinDC,
    cvxHQ,
    pnlMemphis,
    pnlJackson,
  ] = await db
    .insert(sitesTable)
    .values([
      {
        customerId: nexatek.id,
        siteName: 'Nexatek Corporate HQ',
        address1: '2400 N Pearl St',
        city: 'Dallas',
        state: 'TX',
        postalCode: '75201',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'NXT-TX-HQ',
        notes: 'Primary trading floor. Latency SLA < 3ms to exchange colocation.',
        latitude: 32.7918,
        longitude: -96.8036,
        geoSource: 'imported' as const,
      },
      {
        customerId: nexatek.id,
        siteName: 'Nexatek Data Center (DFW)',
        address1: '1901 N Stemmons Fwy',
        city: 'Dallas',
        state: 'TX',
        postalCode: '75207',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'NXT-TX-DC1',
        notes: 'Colocation cage in Equinix DA1. Dual-homed Zayo + Lumen.',
        latitude: 32.7849,
        longitude: -96.8157,
        geoSource: 'imported' as const,
      },
      {
        customerId: nexatek.id,
        siteName: 'Nexatek Warehouse',
        address1: '800 E Mockingbird Ln',
        city: 'Irving',
        state: 'TX',
        postalCode: '75062',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'NXT-TX-WH1',
        lconName: 'Marcus Webb',
        lconPhone: '+1 972-555-0142',
        lconEmail: 'm.webb@nexatek.com',
        latitude: 32.8141,
        longitude: -96.9698,
        geoSource: 'imported' as const,
      },
      {
        customerId: nexatek.id,
        siteName: 'Nexatek Denver Warehouse',
        address1: '4600 E 48th Ave',
        city: 'Denver',
        state: 'CO',
        postalCode: '80216',
        country: 'US',
        timezone: 'America/Denver',
        siteCode: 'NXT-CO-DEN',
        notes:
          'Distribution warehouse. Comcast Business primary, AT&T LTE failover. WAN1 currently down — failover active.',
        lconName: 'Diane Kowalski',
        lconPhone: '+1 720-555-0388',
        lconEmail: 'd.kowalski@nexatek.com',
        latitude: 39.787,
        longitude: -104.918,
        geoSource: 'imported' as const,
      },
      {
        customerId: nexatek.id,
        siteName: 'Nexatek Austin Office',
        address1: '500 W 5th St',
        city: 'Austin',
        state: 'TX',
        postalCode: '78701',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'NXT-TX-AUS',
        notes:
          'Regional sales office. AT&T Business Fiber primary, Spectrum backup. AutoVPN to HQ.',
        latitude: 30.2672,
        longitude: -97.7453,
        geoSource: 'imported' as const,
      },
      {
        customerId: nexatek.id,
        siteName: 'Nexatek Phoenix Retail',
        address1: '1 E Washington St',
        city: 'Phoenix',
        state: 'AZ',
        postalCode: '85004',
        country: 'US',
        timezone: 'America/Phoenix',
        siteCode: 'NXT-AZ-PHX',
        notes:
          'Retail location. Cox Business primary, Verizon LTE backup. Recently upgraded to MX 18.211.',
        latitude: 33.4484,
        longitude: -112.074,
        geoSource: 'imported' as const,
      },
      {
        customerId: ridgeline.id,
        siteName: 'Ridgeline Nashville Medical Center',
        address1: '2400 Patterson St',
        city: 'Nashville',
        state: 'TN',
        postalCode: '37203',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'RDG-TN-NMC',
        notes:
          'Main hospital campus. EHR system hosted on-site. Fiber only — no wireless fallback.',
        lconName: 'Patricia Nguyen',
        lconPhone: '+1 615-555-0277',
        lconEmail: 'p.nguyen@ridgelinehealth.com',
        latitude: 36.1476,
        longitude: -86.8112,
        geoSource: 'imported' as const,
      },
      {
        customerId: ridgeline.id,
        siteName: 'Ridgeline Knoxville Clinic',
        address1: '500 S Gay St',
        city: 'Knoxville',
        state: 'TN',
        postalCode: '37902',
        country: 'US',
        timezone: 'America/New_York',
        siteCode: 'RDG-TN-KNX',
        lconName: 'Tom Aldridge',
        lconPhone: '+1 865-555-0519',
        latitude: 35.9606,
        longitude: -83.9207,
        geoSource: 'imported' as const,
      },
      {
        customerId: broadfields.id,
        siteName: 'Broadfields Chicago Distribution',
        address1: '1300 W Carroll Ave',
        city: 'Chicago',
        state: 'IL',
        postalCode: '60607',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'BRF-IL-DC1',
        notes:
          'Regional distribution center. 50+ POS terminals. Mission-critical during business hours.',
        lconName: 'Jerome Hutchins',
        lconPhone: '+1 312-555-0631',
        lconEmail: 'jhutchins@broadfields.com',
        latitude: 41.8827,
        longitude: -87.6562,
        geoSource: 'imported' as const,
      },
      {
        customerId: broadfields.id,
        siteName: 'Broadfields Rockford Store',
        address1: '4420 E State St',
        city: 'Rockford',
        state: 'IL',
        postalCode: '61108',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'BRF-IL-RFD',
        latitude: 42.2711,
        longitude: -89.094,
        geoSource: 'imported' as const,
      },
      {
        customerId: convergex.id,
        siteName: 'ConvergeX Austin Colocation',
        address1: '9220 Waterford Centre Blvd',
        city: 'Austin',
        state: 'TX',
        postalCode: '78758',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'CVX-TX-AUS-DC',
        notes: 'QTS Austin Data Center. Primary production environment.',
        latitude: 30.3981,
        longitude: -97.7119,
        geoSource: 'imported' as const,
      },
      {
        customerId: convergex.id,
        siteName: 'ConvergeX HQ',
        address1: '701 Brazos St',
        city: 'Austin',
        state: 'TX',
        postalCode: '78701',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'CVX-TX-HQ',
        latitude: 30.2655,
        longitude: -97.7393,
        geoSource: 'imported' as const,
      },
      {
        customerId: pinnacle.id,
        siteName: 'Pinnacle Memphis Terminal',
        address1: '3575 Tchoupitoulas St',
        city: 'Memphis',
        state: 'TN',
        postalCode: '38127',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'PNL-TN-MEM',
        notes: 'Primary dispatch terminal. Wireless backup via Cradlepoint.',
        lconName: 'Reggie Fontenot',
        lconPhone: '+1 901-555-0824',
        lconEmail: 'rfontenot@pinnaclelogistics.com',
        latitude: 35.2271,
        longitude: -90.0415,
        geoSource: 'imported' as const,
      },
      {
        customerId: pinnacle.id,
        siteName: 'Pinnacle Jackson Yard',
        address1: '201 E Pascagoula St',
        city: 'Jackson',
        state: 'MS',
        postalCode: '39201',
        country: 'US',
        timezone: 'America/Chicago',
        siteCode: 'PNL-MS-JAX',
        notes: 'Remote yard site. Limited IT presence.',
        latitude: 32.2988,
        longitude: -90.1848,
        geoSource: 'imported' as const,
      },
    ])
    .returning();

  return {
    nxtHQ,
    nxtDC,
    nxtWarehouse,
    nxtDenver,
    nxtAustin,
    nxtPhoenix,
    rdgNashville,
    rdgKnoxville,
    brfChicago,
    brfRockford,
    cvxAustinDC,
    cvxHQ,
    pnlMemphis,
    pnlJackson,
  };
}
