import { Router, type IRouter } from 'express';
import healthRouter from './health';
import authRouter from './auth';
import customersRouter from './customers';
import sitesRouter from './sites';
import servicesRouter from './services';
import ticketsRouter from './tickets';
import slaPoliciesRouter from './sla-policies';
import usersRouter from './users';
import dashboardRouter from './dashboard';
import controllersRouter from './controllers';
import devicesRouter from './devices';
import networkLinksRouter from './network-links';
import deviceEventsRouter from './device-events';
import contactsRouter from './contacts';
import escalationNotificationsRouter from './escalation-notifications';
import escalationMatrixRouter from './escalation-matrix';
import partnersRouter from './partners';
import salesforceRouter from './salesforce';
import integrationsInvoxaiRouter from './integrations-invoxai';
import invoiceComplaintsRouter from './invoice-complaints';
import avalaraRouter from './avalara';
import publicNetworkMapRouter from './public-network-map';
import monitoringTargetsRouter from './monitoring-targets';
import dnsCandidatesRouter from './dns-candidates';

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(customersRouter);
router.use(sitesRouter);
router.use(servicesRouter);
router.use(ticketsRouter);
router.use(slaPoliciesRouter);
router.use(usersRouter);
router.use(dashboardRouter);
router.use(controllersRouter);
router.use(devicesRouter);
router.use(networkLinksRouter);
router.use(deviceEventsRouter);
router.use(contactsRouter);
router.use(escalationNotificationsRouter);
router.use(escalationMatrixRouter);
router.use(partnersRouter);
router.use(salesforceRouter);
router.use(integrationsInvoxaiRouter);
router.use(invoiceComplaintsRouter);
router.use(avalaraRouter);
router.use(publicNetworkMapRouter);
router.use(monitoringTargetsRouter);
router.use(dnsCandidatesRouter);

export default router;
